### ISSUE TITLE
Test script fails when unrelated scripts are present in dist folders

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-scripts#17]
**Describe the bug**
`jest` fails when already packaged scripts are present in folders like `public` and `dist`.

**To Reproduce**
1. Add `monaco-editor` to your project, and copy its AMD distribution to `public` and `dist.
2. Run `operational-scripts test`.
3. See the terminal output below:

```
Documents/contiamo/pantheon-ui on  fix/cancel-olap-query [$!?] is 📦  v3.0.1 via ⬢ v8.9.2 took 3s
➜ yarn test
yarn run v1.9.4
$ operational-scripts test
SyntaxError: Invalid regular expression: /(/__tests__/.*|\.(test|spec))(?<!d)\.(ts|tsx)$/: Invalid group
    at new RegExp (<anonymous>)
    at regexToMatcher (/Users/peterszerzo/Documents/contiamo/pantheon-ui/node_modules/jest-cli/build/SearchSource.js:104:17)
    at new SearchSource (/Users/peterszerzo/Documents/contiamo/pantheon-ui/node_modules/jest-cli/build/SearchSource.js:140:18)
    at /Users/peterszerzo/Documents/contiamo/pantheon-ui/node_modules/jest-cli/build/runJest.js:155:20
    at Generator.next (<anonymous>)
    at step (/Users/peterszerzo/Documents/contiamo/pantheon-ui/node_modules/jest-cli/build/runJest.js:107:30)
    at /Users/peterszerzo/Documents/contiamo/pantheon-ui/node_modules/jest-cli/build/runJest.js:126:14
    at new Promise (<anonymous>)
    at /Users/peterszerzo/Documents/contiamo/pantheon-ui/node_modules/jest-cli/build/runJest.js:104:12
    at getTestPaths (/Users/peterszerzo/Documents/contiamo/pantheon-ui/node_modules/jest-cli/build/runJest.js:192:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Folders like `public` and `dist` are ignored, so one can add any scripts and packages in there without causing `jest` to throw errors. 

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by fabien0102** [comment]
And to add a bit more information on this strange behaviour, it works perfectly on my computer (window 10, node v8.11.1)

**Comment by peterszerzo** [comment]
@ImogenF a `brew upgrade node` should do the trick :)
